package com.miaolegemitong.demo.thrift.client;

import com.miaolegemitong.demo.thrift.client.autogenerated.DemoObject;
import com.miaolegemitong.demo.thrift.client.autogenerated.DemoSerivce;
import com.miaolegemitong.demo.thrift.client.utils.ThriftConfig;
import com.miaolegemitong.demo.thrift.client.utils.ThriftProxyFactory;
import org.apache.thrift.TException;

/**
 * @author miaolegemitong
 * @email mitong1993@gmail.com
 * @date 2016/12/12
 * @description 通过代理调用服务
 */
public class JavaClientProxy {
    public static void main(String[] args) throws TException {
        //配置
        ThriftConfig config = new ThriftConfig();
        config.setHost("127.0.0.1");
        // TODO: 2016/12/9 修改端口号到服务的端口号
        int port = 10000;
        config.setPort(port);
        //创建代理对象
        DemoSerivce.Iface proxy = (DemoSerivce.Iface) ThriftProxyFactory.createProxy(DemoSerivce.Client.class, config);
        //调用方法
        String ret = proxy.ping("test");
        System.out.println(ret);
        DemoObject objectRet = proxy.getObject("xxx", 2);
        System.out.println(objectRet.getX() + "\t" + objectRet.getY());
    }
}
