package com.miaolegemitong.demo.thrift.server;

import com.miaolegemitong.demo.thrift.server.autogenerated.DemoSerivce;
import com.miaolegemitong.demo.thrift.server.autogenerated.DemoObject;
import org.apache.thrift.TException;

/**
 * @author miaolegemitong
 * @email mitong1993@gmail.com
 * @date 2016/12/7
 * @description 服务的具体实现
 */
public class DemoImpl implements DemoSerivce.Iface {
    @Override
    public String ping(String param) throws TException {
        // TODO: 2016/12/9 此处实现服务需要执行的代码
        return "Got ping request: " + param;
    }

    @Override
    public DemoObject getObject(String x, int y) throws TException {
        // TODO: 2016/12/9 此处实现服务需要执行的代码
        return new DemoObject(x, y);
    }
}
