package com.miaolegemitong.demo.thrift.server;

import com.miaolegemitong.demo.thrift.server.autogenerated.DemoSerivce;
import org.apache.thrift.protocol.TBinaryProtocol.Factory;
import org.apache.thrift.server.TServer;
import org.apache.thrift.server.TThreadPoolServer;
import org.apache.thrift.server.TThreadPoolServer.Args;
import org.apache.thrift.transport.TServerSocket;
import org.apache.thrift.transport.TTransportException;

/**
 * @author miaolegemitong
 * @email mitong1993@gmail.com
 * @date 2016/12/7
 * @description 服务启动类，使用assembly打包上传到服务器之后执行此类代码即可启动服务
 */
public class DemoServer {
    public void startServer() {
        try {
            //此处定义服务所用的端口
            int port = 10000;
            TServerSocket serverTransport = new TServerSocket(port);
            DemoSerivce.Processor<DemoImpl> process = new DemoSerivce.Processor<>(new DemoImpl());
            Factory portFactory = new Factory(true, true);
            Args args = new Args(serverTransport);
            args.processor(process);
            args.protocolFactory(portFactory);
            TServer server = new TThreadPoolServer(args);
            server.serve();
        } catch (TTransportException e) {
            e.printStackTrace();
        }
    }

    public static void main(String[] args) {
        DemoServer server = new DemoServer();
        server.startServer();
    }
}
