package com.miaolegemitong.demo.springboot.dao;

import com.miaolegemitong.demo.springboot.model.DemoPO;
import com.miaolegemitong.demo.springboot.model.DemoPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface DemoPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_table
     *
     * @mbggenerated Fri Jun 16 17:43:11 CST 2017
     */
    @SelectProvider(type=DemoPOSqlProvider.class, method="countByExample")
    int countByExample(DemoPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_table
     *
     * @mbggenerated Fri Jun 16 17:43:11 CST 2017
     */
    @DeleteProvider(type=DemoPOSqlProvider.class, method="deleteByExample")
    int deleteByExample(DemoPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_table
     *
     * @mbggenerated Fri Jun 16 17:43:11 CST 2017
     */
    @Delete({
        "delete from demo_table",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_table
     *
     * @mbggenerated Fri Jun 16 17:43:11 CST 2017
     */
    @Insert({
        "insert into demo_table (id, name, ",
        "password)",
        "values (#{id,jdbcType=INTEGER}, #{name,jdbcType=VARCHAR}, ",
        "#{password,jdbcType=VARCHAR})"
    })
    int insert(DemoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_table
     *
     * @mbggenerated Fri Jun 16 17:43:11 CST 2017
     */
    @InsertProvider(type=DemoPOSqlProvider.class, method="insertSelective")
    int insertSelective(DemoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_table
     *
     * @mbggenerated Fri Jun 16 17:43:11 CST 2017
     */
    @SelectProvider(type=DemoPOSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR)
    })
    List<DemoPO> selectByExample(DemoPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_table
     *
     * @mbggenerated Fri Jun 16 17:43:11 CST 2017
     */
    @Select({
        "select",
        "id, name, password",
        "from demo_table",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR)
    })
    DemoPO selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_table
     *
     * @mbggenerated Fri Jun 16 17:43:11 CST 2017
     */
    @UpdateProvider(type=DemoPOSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") DemoPO record, @Param("example") DemoPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_table
     *
     * @mbggenerated Fri Jun 16 17:43:11 CST 2017
     */
    @UpdateProvider(type=DemoPOSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") DemoPO record, @Param("example") DemoPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_table
     *
     * @mbggenerated Fri Jun 16 17:43:11 CST 2017
     */
    @UpdateProvider(type=DemoPOSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(DemoPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table demo_table
     *
     * @mbggenerated Fri Jun 16 17:43:11 CST 2017
     */
    @Update({
        "update demo_table",
        "set name = #{name,jdbcType=VARCHAR},",
          "password = #{password,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(DemoPO record);
}