package com.miaolegemitong.demo.springboot.model;

public class DemoPO {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_table.id
     *
     * @mbggenerated Fri Jun 16 17:43:11 CST 2017
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_table.name
     *
     * @mbggenerated Fri Jun 16 17:43:11 CST 2017
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo_table.password
     *
     * @mbggenerated Fri Jun 16 17:43:11 CST 2017
     */
    private String password;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_table.id
     *
     * @return the value of demo_table.id
     *
     * @mbggenerated Fri Jun 16 17:43:11 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_table.id
     *
     * @param id the value for demo_table.id
     *
     * @mbggenerated Fri Jun 16 17:43:11 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_table.name
     *
     * @return the value of demo_table.name
     *
     * @mbggenerated Fri Jun 16 17:43:11 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_table.name
     *
     * @param name the value for demo_table.name
     *
     * @mbggenerated Fri Jun 16 17:43:11 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo_table.password
     *
     * @return the value of demo_table.password
     *
     * @mbggenerated Fri Jun 16 17:43:11 CST 2017
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo_table.password
     *
     * @param password the value for demo_table.password
     *
     * @mbggenerated Fri Jun 16 17:43:11 CST 2017
     */
    public void setPassword(String password) {
        this.password = password;
    }
}